if(NOT SAMPLE)
    message(FATAL_ERROR "SAMPLE is not defined!")
endif()

if(NOT SAMPLE_SRCFILES)
	set(SAMPLE_SRCFILES main.cpp)
endif()

add_executable(${SAMPLE} ${SAMPLE_SRCFILES})

TARGET_LINK_LIBRARIES(${SAMPLE} PRIVATE restinio::restinio)
TARGET_INCLUDE_DIRECTORIES(${SAMPLE} PRIVATE ${CMAKE_SOURCE_DIR}/args)

if(WIN32)
	TARGET_LINK_LIBRARIES(${SAMPLE} wsock32 ws2_32)
endif()


install(TARGETS ${SAMPLE} DESTINATION bin)
