if(NOT TEST_BENCH)
	message(FATAL_ERROR "TEST_BENCH is not defined!")
endif()

if(NOT TEST_BENCH_SRCFILES)
	set(TEST_BENCH_SRCFILES main.cpp)
endif()

add_executable(${TEST_BENCH} ${TEST_BENCH_SRCFILES})

TARGET_LINK_LIBRARIES(${TEST_BENCH} PRIVATE restinio::restinio)
TARGET_INCLUDE_DIRECTORIES(${TEST_BENCH} PRIVATE ${CMAKE_SOURCE_DIR}/args)

if(WIN32)
	TARGET_LINK_LIBRARIES(${TEST_BENCH} wsock32 ws2_32)
endif()

IF (RESTINIO_INSTALL_BENCHES)
	install(TARGETS ${TEST_BENCH} DESTINATION bin)
ENDIF ()
