if(NOT UNITTEST)
	message(FATAL_ERROR "UNITTEST is not defined!")
endif()

if(NOT UNITTEST_SRCFILES)
	set(UNITTEST_SRCFILES main.cpp)
endif()

add_executable(${UNITTEST} ${UNITTEST_SRCFILES})

TARGET_LINK_LIBRARIES(${UNITTEST} PRIVATE restinio::restinio)
TARGET_INCLUDE_DIRECTORIES(${UNITTEST} PRIVATE ${CMAKE_SOURCE_DIR})

if(WIN32)
	TARGET_LINK_LIBRARIES(${UNITTEST} PRIVATE wsock32 ws2_32)
endif()

add_test(NAME ${UNITTEST} COMMAND ${UNITTEST})
