# Usage example:
set(RESTINIO_LIB_VERSION_MAJOR 0)
set(RESTINIO_LIB_VERSION_MINOR 7)
set(RESTINIO_LIB_VERSION_PATCH 0)

set(RESTINIO_LIB_VERSION
    ${RESTINIO_LIB_VERSION_MAJOR}.${RESTINIO_LIB_VERSION_MINOR}.${RESTINIO_LIB_VERSION_PATCH})

set(TARGET_LIB_SOVERSION ${RESTINIO_LIB_VERSION_MAJOR}.${RESTINIO_LIB_VERSION_MINOR})

message(STATUS "RESTINIO_LIB_VERSION  : " ${RESTINIO_LIB_VERSION})
message(STATUS "RESTINIO_LIB_SOVERSION: " ${RESTINIO_LIB_SOVERSION})
